Add mypy typings
nMustaki/debinterface pull request #40
Opened 2021-03-10 10:44 UTC by ObjatieGroba

2021-03-14 15:58 UTC, ObjatieGroba commented
Would it better to do it on 3.5.0 version?

2021-03-15 21:00 UTC, nMustaki requested changes
I'm all to put into 3.5, it's a great feature, the sooner the better !

2021-03-16 10:27 UTC, ObjatieGroba commented on debinterface/interfaces.py
> +import typing as tp
Should it be?

Python 3.5 and later contains typing as build-in module. For other it is possible to specify `typing;python_version<"3.5"` requirement.

I do not really sure what is the best way

2021-03-20 13:20 UTC, nMustaki commented on debinterface/interfaces.py
> +import typing as tp
I'd like to avoid adding a dependency if possible, as long as we support python2

2021-03-24 20:33 UTC, nMustaki approved these changes

2021-06-22 09:53 UTC, merged