Improvement spaces at attrs value
nMustaki/debinterface pull request #41
Opened 2021-03-15 09:22 UTC by ObjatieGroba

2021-03-15 20:47 UTC, nMustaki requested changes
Let's clean it up more

2021-03-15 20:47 UTC, nMustaki commented on debinterface/interfacesReader.py
> +            sline = [x.strip() for x in line.split(None, 1)]
I'm not keen of it because it would no longer clean the rest of line.
Also, there is some code in the if/else which expects a list, they would need to be modified.

Rereading the code, it seems to me we can cleanup things by creating properly two variables:

```suggestion
            sline = [x.strip() for x in line.split()]
            try:
                keyword, argument = sline[0], " ".join(sline[:1])
            except IndexError:
                raise ValueError("Line {} is missing parameter".format(sline))
```

And then using them in the if/else:

```python
            if keyword == 'address':
                self._adapters[self._context].setAddress(argument)
            elif keyword == 'netmask':
                self._adapters[self._context].setNetmask(argument)
            elif keyword == 'gateway':
                self._adapters[self._context].setGateway(argument)
            elif keyword == 'broadcast':
                self._adapters[self._context].setBroadcast(argument)
            elif keyword == 'network':
                self._adapters[self._context].setNetwork(argument)
            elif keyword == 'hostapd':
                self._adapters[self._context].setHostapd(argument)
            elif keyword == 'wpa-conf':
                self._adapters[self._context].setWpaConf(argument)
            elif keyword == 'dns-nameservers':
                self._adapters[self._context].setDnsNameservers(argument)
            elif keyword == 'dns-search':
                self._adapters[self._context].setDnsSearch(argument)
            elif keyword.startswith('bridge') is True:
                opt = keyword.split('_')
                self._adapters[self._context].replaceBropt(opt[1], argument)
            elif keyword == 'up':
                self._adapters[self._context].appendUp(argument)
            elif keyword == 'down':
                self._adapters[self._context].appendDown(argument)
            elif keyword == 'pre-up':
                self._adapters[self._context].appendPreUp(argument)
            elif keyword == 'pre-down':
                self._adapters[self._context].appendPreDown(argument)
            elif keyword == 'post-up':
                self._adapters[self._context].appendPostUp(argument)
            elif keyword == 'post-down':
                self._adapters[self._context].appendPostDown(argument)
            else:
                # store as if so as not to loose it
                self._adapters[self._context].setUnknown(keyword, argument)

```

What do you think ?

2021-03-16 10:12 UTC, ObjatieGroba commented on debinterface/interfacesReader.py
> +            sline = [x.strip() for x in line.split(None, 1)]
I do not think that we should do it your way.

Firstly - current version loses params after spaces.
Secondly, your new version will reformat value that never uses/changes.

Trailing spaces is not nice.

Suggestion: `attribute, value = line.strip().split(None, 1)`

2021-03-16 10:17 UTC, ObjatieGroba commented on debinterface/interfacesReader.py
> +            sline = [x.strip() for x in line.split(None, 1)]
> Also, there is some code in the if/else which expects a list, they would need to be modified.

Ok, I will refactor them

Maybe functions like `up` should do split by themselves. Shouldn't them? We know for sure for them that spaces does not matter

2021-03-20 13:30 UTC, nMustaki commented on debinterface/interfacesReader.py
> +            sline = [x.strip() for x in line.split(None, 1)]
These are good suggestions, go ahead

2021-03-24 20:24 UTC, nMustaki approved these changes
That's ok !

2021-03-24 20:25 UTC, nMustaki commented
@ObjatieGroba that one was planned for the 3.6, but we may merge it now, what do you think ?

2021-03-24 20:26 UTC, merged